Bugfix for build exception in Node v13.13+ (#287)
After the update to `@babel/preset-env` `^7.8.6"` I faced the exception during the build on a plain machine:
```
ERROR in ./core/service-worker/index.js Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
```

I've found this issue mentioned in the latest commits of the `babel` plugin and upgraded to `7.9.0` as recommended: https://github.com/babel/babel/pull/11283 and https://github.com/nodejs/node/issues/32852